Cheapest Area = 
VAR MinPrice = MINX(ALLSELECTED('Private Rent Index'[Area name]), [Average Rental Price])
RETURN FILTER(ALLSELECTED('Private Rent Index'[Area-Region]), [Average Rental Price] = MinPrice)
